on:
  push:
    paths:
      - 'source/**'

name: CreatePDFs

jobs:
  makepdfs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: mkrakowitzer/actions-makepdfs@master
      if: github.ref == 'refs/heads/master'
      with:
        markdown_dir: source
        output_dir: tmp
    - uses: actions/upload-artifact@v3
      with:
        name: output-docs
        path: tmp